### ISSUE TITLE
I2C library not working 

### ISSUE THREAD

**Issue by sylim5442** [CytronTechnologies/LCM1602-14_LCD_Library_Arduino#1]
I used I2C arduino library and the example "Hello World" sketch is only showing a single H letter without the rest. 
I can manipulate the location of "H" by changing cursor but that is all. 
The product is LCM1602A-14 bought from Cytron. 
Pls sort out this problem.

**Comment by oberchoo** [comment]
Hi, which microcontroller are you using and mind showing the connection? You can share pictures and links at our forum here: https://forum.cytron.io/

Meantime, we have also released a simple tutorial using NodeMCU, ESP2866 to display the message on this LCD with Arduino library and example: https://tutorial.cytron.io/2021/05/15/displaying-telegram-message-on-3-3v-serial-lcd-using-nodemcu-esp8266/

**Comment by oberchoo** [comment]
Hi, we have updated the library and verify with Maker UNO. Please try it again.

**Comment by sylim5442** [comment]
Hi thank you the I2C library works now. 
[Arduino UNO]
