### ISSUE TITLE
how to display numbers

### ISSUE THREAD

**Issue by conradwee** [CytronTechnologies/LCM1602-14_LCD_Library_Arduino#2]
I am unable to display numbers through variables such as int and float through LCD.print().
I only display outputs of chinese characters instead

Any help?

**Comment by Bhavithiran97** [comment]
Can share the code ?

**Comment by conradwee** [comment]
#include <lcd_i2c.h> //Import lcd_i2c library


lcd_i2c lcd(0x3E,16,2); //The I2C communication for this LCD is 0x3E (HEX) or 62 (DEC), 16 is the number of the columns, 2 is the number of the rows

void setup()
{
  lcd.begin(); //LCD initialization function  
}

void loop() 
{
  int a = 5;
      lcd.setCursor(0, 0); //cursor setting function start with column followed by row
    lcd.print(a); //Print text
    delay(500);
  // Do nothing here
}

**Comment by conradwee** [comment]
thanks for the help! I intend to read the value from a sensor and output, not sure what is the data type the value should be

**Comment by Bhavithiran97** [comment]
The value should be in char data type. Must convert the integer to char

**Comment by conradwee** [comment]
Thanks!
